source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KKGallery_Example', :exclusive => true do
  pod "KKGallery", :path => "../"
  pod 'MBProgressHUD', '~> 0.9'
  pod 'RFQuiltLayout', '~> 1.1'
end

target 'KKGallery_Tests', :exclusive => true do
  pod "KKGallery", :path => "../"
  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
